### ISSUE TITLE
Cannot connect with Stripe

### ISSUE THREAD

**Issue by PixievoltNo1** [stackaid/stackaid#10]
When I try to claim my projects, clicking "Setup new deposit" gets "There was an error setting up payment." This appeared right on the page without my browser getting redirected.

**Comment by wescarr** [comment]
@PixievoltNo1 Sorry about that. Did you previously start the setup process and then not finish for some reason?

**Comment by PixievoltNo1** [comment]
Issue was resolved over e-mail. Thanks!
