### ISSUE TITLE
Why not making this open source?

### ISSUE THREAD

**Issue by pombredanne** [stackaid/stackaid#5]
I find it weird that this is not FOSS code. Care to elaborate why?

**Comment by voxpelli** [comment]
What benefits would there be in this being open source?

**Comment by wescarr** [comment]
@pombredanne There are parts of StackAid that we do plan to open source, but as you know it takes a lot of time and effort to do that properly. As @voxpelli says, open sourcing all of StackAid wouldn't provide much utility.

**Comment by wescarr** [comment]
If there are other questions/comments about our position/views here feel free to re-open, but I am closing this for now.

**Comment by pombredanne** [comment]
Your call, but I am puzzled by how you benefit from open source and are helping funding open source and but you do not think that being open source is good enough for you?
