### ISSUE TITLE
Analysis of packages doesn't seem reliable

### ISSUE THREAD

**Issue by romainmenke** [stackaid/stackaid#8]
```
curl 'https://www.stackaid.us/api/v1/analyze' \
-X 'POST' \
-H 'Content-Type: application/json' \
--data-binary '{"dependencies":{"postcss-preset-env":"^8.0.0"}}'
```

Responds with `{"projects":[]}`

-----

version `6.7.0` was from before the mono repo and does contain meaningful contents.

```
curl 'https://www.stackaid.us/api/v1/analyze' \
-X 'POST' \
-H 'Content-Type: application/json' \
--data-binary '{"dependencies":{"postcss-preset-env":"^6.7.0"}}'
```

Edit : versions like `7.4.0` seems to also work correctly and then the package was already moved to the monorepo.
Maybe more an issue with these latest versions?

-----

_No idea if this is the right channel for support :)_

**Comment by wescarr** [comment]
@romainmenke Our npm change feed processing pipeline got behind but should be caught up now. I just tried your query and get the expected results. Please let us know if you see another issues and apologies for the late response!

**Comment by romainmenke** [comment]
Thank you for the reply!

We have since had a bunch of feature releases
and seeing the same empty response for `8.1`, `8.2`, `8.3` and `8.3.1`.

But it is good to know that this should resolve itself :)

**Comment by wescarr** [comment]
@romainmenke I'll check out change feed, thanks for letting me know! We will get it sorted out.

**Comment by wescarr** [comment]
@romainmenke Just wanted to follow up that we've caught on npm package releases. Please let us know if you have any other issues.

**Comment by romainmenke** [comment]
Everything seems good now!
Thank you for following up on this 🙇
